routes/web.php
<?php

use App\Http\Controllers\PhoneController;
use App\Http\Cotrollers;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'App\Http\Controllers\PhoneController@index')->name('phones');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::resource('profile', 'App\Http\Controllers\ProfileController');
Route::resource('phones', 'App\Http\Controllers\PhoneController');
Route::resource('categories', 'App\Http\Controllers\CategoryController');
Route::put('/phones/update/{id}', [PhoneController::class, 'update'])->name('phones.update');
Route::get('/phones/edit/{id}', [PhoneController::class, 'edit'])->name('phones.edit');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'username',
        'avatar'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/users/profile.blade.php
@extends('layouts.layout')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"> Edit user Information</div>

                    <div class="card-body">

                        @if(count($errors)>0)
                            <ul class="navbar-nav mr-auto">
                                @foreach ($errors->all() as $error)
                                    <li class="nav-item active">
                                        {{$error}}
                                    </li>
                                @endforeach

                            </ul>
                        @endif

                        <form action="{{route('profile.update', $user->id)}}" method="POST" enctype="multipart/form-data" >
                            {{ csrf_field()}}
                            {{ method_field('PATCH') }}

                            <input name="id" type="hidden" value="{{ $user->id }}">

                            <div class="form-group">
                                <label for="avatar">Update Profile Image</label>
                                <input type="file" class="form-control-file" name=avatar>
                            </div>

                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" name="name"  value="{{$user->name}}">
                            </div>

                            <div class="form-group">
                                <label for="name">Username</label>
                                <input type="text" class="form-control" name="username"  value="{{$user->username}}">
                            </div>

                            <div class="form-group">
                                <label for="name">Email Address</label>
                                <input type="text" class="form-control" name="email"  value="{{$user->email}}">
                            </div>

                            <button type="submit" class="btn btn-primary">Update</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection