routes/web.php
<?php

use App\Http\Controllers\PhoneController;
use App\Http\Cotrollers;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'App\Http\Controllers\PhoneController@index')->name('phones');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::resource('profile', 'App\Http\Controllers\ProfileController');
Route::resource('phones', 'App\Http\Controllers\PhoneController');
Route::resource('categories', 'App\Http\Controllers\CategoryController');
Route::put('/phones/update/{id}', [PhoneController::class, 'update'])->name('phones.update');
Route::get('/phones/edit/{id}', [PhoneController::class, 'edit'])->name('phones.edit');

app/Models/Phone.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Category;

class Phone extends Model
{
    use HasFactory;
    protected $table = 'phones';
    protected $fillable = ['name','category_id','quantity','price','image_path'];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }
}

app/Http/Controllers/PhoneController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePhoneRequest;
use App\Http\Requests\UpdatePhoneRequest;
use App\Http\Requests\UpdateProfileRequest;
use App\Models\Phone;
use Illuminate\Http\Request;
Use App\Models\Category;

class PhoneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $phones = Phone::with('category')->paginate(10);
        return view('phones.index', compact('phones'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::get();
        return view('phones.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreatePhoneRequest $request)
    {
        if($request->hasFile('image_path')) {
            $image_path = request()->file('image_path');
            $extension = $image_path->getClientOriginalExtension();
            $newImageName = time() . '-' . $request->name . '.' . $extension;
            $request->image_path->move(public_path('/uploads/img/'), $newImageName);
        }
        $phone = Phone::create([
            'name' => $request->input('name'),
            'quantity' => $request->input('quantity'),
            'price' => $request->input('price'),
            'image_path' => $newImageName,
            'category_id' => $request->input('category_id')
        ]);

        return redirect()->route('phones.index')->with('success','Phone created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Phone  $phone
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show(Phone $phone)
    {
        return view('phones.show',compact('phone'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Phone  $phone
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit($id)
    {
        $phone=Phone::findOrFail($id);
        $categories=Category::get();
        return view('phones.edit',compact('phone','categories'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdatePhoneRequest $request, $id): \Illuminate\Http\RedirectResponse
    {
        $phone=Phone::findOrFail($id);

        $phone->id = $request->input('id');
        $phone->name = $request->input('name');
        $phone->quantity = $request->input('quantity');
        $phone->price = $request->input('price');
        $phone->category_id = $request->input('category_id');

        if($request->hasFile('image_path')) {
            $image_path = request()->file('image_path');
            $extension = $image_path->getClientOriginalExtension();
            $filename = time() . '-' . $request->name . '.' . $extension;
            $image_path->move(public_path('/uploads/img/'), $filename);
            $phone->update(['image_path' => $filename]);
        }
        $phone->update();
        return redirect()->route('phones.index')->with('success','Entry updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {

        Phone::destroy($id);
        return redirect()->route('phones.index')->with('success','Phone deleted successfully');
    }

    public function __construct()
    {
        $this->middleware('auth');
    }


}

resources/views/phones/create.blade.php
@extends('layouts.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2><strong>Create a new entry</strong></h2>
                <hr>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
        <strong>Whoops!</strong> something we are problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
        </div>
    @endif
    <form action="{{ route('phones.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row ">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Category:</strong>
                    <select name="category_id" class="form-control">
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <strong>Quantity:</strong>
                <input type="number"  name="quantity" class="form-control" placeholder="Quantity">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <strong>Price per unit:</strong>
                <input type="number"  name="price" class="form-control" placeholder="Price">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <strong>Image:</strong>
                <input type="file"  name="image_path" class="form-control-file">
                </div>
            </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-success">Submit</button>
            <a class="btn btn-primary" href="{{ route('phones.index') }}">Back</a>
        </div>
    </div>
    </form>
@endsection

resources/views/phones/edit.blade.php
@extends('layouts.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2><strong>Edit an entry</strong></h2>
                <hr>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> something we are problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('phones.update',$phone->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
        <input name="id" type="hidden" value="{{ $phone->id }}">

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" value="{{ $phone->name }}" class="form-control" placeholder="Name">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                    <strong>Category:</strong>
                    <select name="category_id" class="form-control">
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}"
                            {{ $category->id == $phone->category_id ? 'selected' : '' }}>
                                {{ $category->name }}</option>
                        @endforeach
                    </select>
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Quantity:</strong>
                <input type="number" name="quantity"  value="{{ $phone->quantity }}" class="form-control" placeholder="Quantity">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Price per unit:</strong>
                <input type="number" name="price"  value="{{ $phone->price }}" class="form-control" placeholder="Price">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Image: <br> </strong>
                <input type="file" value="{{ $phone->image_path }}" name="image_path">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-success">Update</button>
            <a class="btn btn-primary" href="{{ url()->previous() }}">Back</a>
        </div>

    </div>
    </form>
@endsection

resources/views/phones/index.blade.php
@extends('layouts.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> <strong> Product Information </strong></h2>
                <hr>
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <span>{{ $message }}</span>
    </div>
    @endif
    <table class="table " style="background-color: rgba(0,0,0,0.2); color:white;">
        <tr>
            <th>Name</th>
            <th>Category</th>
            <th>Quantity</th>
            <th>Price per unit</th>
            <th>Action</th>
        </tr>
        @foreach ($phones as $phone)
        <tr>
            <td>{{ $phone->name }}</td>
            <td>{{ $phone->category->name }}</td>
            <td>{{ $phone->quantity }}</td>
            <td>{{ $phone->price }}</td>
            <td><form action="{{ route('phones.destroy',$phone->id) }}" method="POST">
            <a class="btn btn-info" href="{{ route('phones.show',$phone->id) }}">Show</a>
            <a class="btn btn-warning" href="{{ route('phones.edit',$phone->id) }}">Edit</a>
            @csrf
            @method('DELETE')
            <button type="submit" onclick="return confirm('Do you really want to delete this entry?')" class="btn btn-danger">Delete</button>
            </form></td>
        </tr>
        @endforeach
    </table>
{!! $phones->links('pagination::bootstrap-4') !!}
@endsection

resources/views/phones/layout.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Mobile Phones Store</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"/>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Open+Sans&family=Roboto&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Open+Sans&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">  
    <style>
         body {
             background-image: url("https://wallpapercave.com/wp/wp5529280.jpg");
             background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
         }
         table{
             font-family: Roboto;
             font-size: 18px;
         }
         
    </style>
    
    </head>
<body >
<div class="container">
    @yield('content')
</div>
</body>
</html>

resources/views/phones/show.blade.php
@extends('layouts.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h3> <strong>Entry Detail</strong> </h3>
                <hr>
            </div>
        </div>
    </div><br>
    <div class="row justify-content-center">
    <div class="col-sm-5">
        <img
            src="{{ asset('/uploads/img/' . $phone->image_path) }}"
            style="width:70%;height:auto;"
        >
    </div>
    <div class="col-sm-5">
        <br>
        <br>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group" style="font-size:30px">
                <strong>Name:</strong>
                {{ $phone->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group" style="font-size:30px">
                <strong>Category:</strong>
                {{ $phone->category->name  }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group" style="font-size:30px">
                <strong>Quantity:</strong>
                {{ $phone->quantity }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group" style="font-size:30px">
                <strong>Price per unit:</strong>
                {{ $phone->price }}
                <hr>
                <a class="btn btn-primary" href="{{ route('phones.index') }}">Back</a>
            </div>

    </div>
    </div>
@endsection